[build]
  publish = "client/dist"
  command = "cd client && npm ci --legacy-peer-deps || npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"